rpc_product_releases:
  master:
    maas_release: master
    osa_release: master
    rpc_release: master
  newton:
    maas_release: 1.7.0
    osa_release: 3553c048188093c7a8d912cc32c30730536d70d3
    rpc_release: r14.8.0
  ocata:
    maas_release: 1.7.0
    osa_release: 5047124f1fe181306674c60beeccd189252a9d62
    rpc_release: r15.0.0
  pike:
    maas_release: 1.7.0
    osa_release: 5c341a7bada78edab5f3d132d55adb00eaf2413f
    rpc_release: r16.2.0
  queens:
    maas_release: 1.7.2.1
    osa_release: 5dbc4c5b67e67c370b04099c7dce56dd2f559288
    rpc_release: r17.0.0
